### ISSUE TITLE
fail build in case sensitive filesystems (mostly linux)

### ISSUE THREAD

**Issue by sl1pkn07** [FYSETC/SoftwareSerialM#1]
https://github.com/FYSETC/SoftwareSerialM/blob/1fdbb01bd0f0bf46d10e117c3374c84d7c009134/HAL_softserial_STM32F1.cpp#L28

should be `HAL_softserial_STM32F1.h`

linux (most filesystems) have case sensitive filesystems. treat `HAL_softSerial_STM32F1.h` as different file than `HAL_softserial_STM32F1.h` (the S capitalized in `serial` word)

![Screenshot_20190818_193058](https://user-images.githubusercontent.com/462213/63228160-9a34b200-c1ef-11e9-92ae-d10857f6057d.png)

fix the file names in the includes pointed to real filename solve the issue

**Comment by sl1pkn07** [comment]
seems `HAL_softserial_STM32F1.cpp` is the only affected. `HAL_softserial_STM32.cpp`  and `HAL_softserial_LPC1768.cpp` not have this issue (with a fast search in the code)

**Comment by GerogeFu** [comment]
Oh, thanks for report.
